import org.scalatest.FunSuite
import edu.mit.compilers.semantics._
import edu.mit.compilers.parser._
// NOTE these are deprecated now

class TypePropTester extends FunSuite {
  val blankProgram = ASTProgram(
    IdToken("void", 1, 1),
    // No imports
    List(),
    // No fields
    List(),
    // No Method
    List()
  )
  val blankTable = Symbols(blankProgram, parent = None)

  // Expression: test (declared as bool test)
  def testTypeScalar(dtype: ReturnType.Type, typeString: String): Boolean = {
    // First you have to declare it
    // NOTE you need to wrap it in a field declaration
    // (the table describe method gets its parent to find the type
    // from the field... maybe not ideal but whatever)
    val field = ASTFieldDecl(
      // Has a token (NOTE that in the scanner types are checked
      // before keywords, so keyword is mainly keywords that
      // are not types)
      TypeToken(typeString, 0, 0),
      // And a type
      ASTTypeNode(TypeToken(typeString, 0, 0)),
      // And a list of variables
      List(
        ASTScalarDecl(
          IdToken("test", 0, 0),
          ASTIdNode(IdToken("test", 0, 0))
        )
      )
    )

    var table = blankTable
    for (declr <- field.vars) {
      // Unclear where in Julius' code the parent is set but we can assume that he does set it
      declr.parent = Some(field)
      val description = TableInserter.describe(declr)
      table = table.addedScalar(description.asInstanceOf[ScalarDescr])
    }
    // Then you can try and get it
    val location =
      ASTScalarLocation(IdToken("test", 0, 0), ASTIdNode(IdToken("test", 0, 0)))
    location.table = table
    location.id.table = table
    val returnExpected = dtype
    val returnGot = TypeProp.visit(location)
    // println(s"got ${returnGot} from ${table}")
    return returnExpected == returnGot
  }

  test(
    "`TypeProp` test: ScalarLocation of BoolType propagates BoolType"
  ) {
    assert(testTypeScalar(ReturnType.bool, "bool"))
  }

  // Expression: test (declared as int test)
  test(
    "`TypeProp` test: ScalarLocation of IntType propagates IntType"
  ) {
    assert(testTypeScalar(ReturnType.int, "int"))
  }

  def testTypeArray(dtype: ReturnType.Type, typeString: String): Boolean = {
    // Boilerplate generated by github copilot (look at scalar for example)

    val field = ASTFieldDecl(
      // Has a token (NOTE that in the scanner types are checked
      // before keywords, so keyword is mainly keywords that
      // are not types)
      TypeToken(typeString, 0, 0),
      // And a type
      ASTTypeNode(TypeToken(typeString, 0, 0)),
      // And a list of variables
      List(
        ASTArrayDecl(
          IdToken("test", 0, 0),
          ASTIdNode(IdToken("test", 0, 0)),
          // And a size
          ASTIntLiteral(IntToken("1", 0, 0))
        )
      )
    )

    var table = blankTable
    for (declr <- field.vars) {
      declr.parent = Some(field)
      val description = TableInserter.describe(declr)
      table = table.addedArray(description.asInstanceOf[ArrayDescr])
    }
    // Then you can try and get it
    val location =
      ASTArrayLocation(
        IdToken("test", 0, 0),
        ASTIdNode(IdToken("test", 0, 0)),
        ASTIntLiteral(IntToken("0", 0, 0))
      )
    location.table = table
    location.id.table = table
    val returnExpected = dtype
    val returnGot = TypeProp.visit(location)
    return returnExpected == returnGot
  }

  // Expression: test[0] (declared as bool test[1])
  // TODO: find out why this fails
  test("`TypeProp` test: ArrayLocation of BoolType propagates BoolType") {
    assert(testTypeArray(ReturnType.bool, "bool"))
  }

  // Expression: test[0] (declared as int test[1])
  // TODO: find out why this fails
  test("`TypeProp` test: ArrayLocation of IntType propagates IntType") {
    assert(testTypeArray(ReturnType.int, "int"))
  }

  def testTypeMethod(dtype: ReturnType.Type, typeString: String): Boolean = {
    // We must have a method declaration
    // Which then we imagine was "visited"
    // and thus loaded into the table
    // Then we have an expression (differnet from the declaration)
    // that we test for return type (should go into the table and find the
    // return type of the declaration)

    // token: Keyword,
    // id: IdNode,
    // params: List[Param],
    // block: Block
    val declr: ASTTypeMethodDecl = ASTTypeMethodDecl(
      // Token
      TypeToken(typeString, 0, 0),
      // Type
      ASTTypeNode(TypeToken(typeString, 0, 0)),
      // Method name
      ASTIdNode(IdToken("test", 0, 0)),
      // No arguments
      List(),
      // Declaration
      ASTBlock(
        // Methods must start like this
        Mark("{", 0, 0),
        // No fields
        List(),
        // No statements
        List()
      )
    )

    // Technically not legal, so might not pass later, but whatever
    val expr: ASTMethodCallExpr = ASTMethodCallExpr(
      // Token
      IdToken("test", 0, 0),
      // MethodName (not sure why it was just IdNode for declr)
      ASTMethodName(
        // Token
        IdToken("test", 0, 0),
        // Id node with token in it
        ASTIdNode(IdToken("test", 0, 0))
      ),
      // Arguments (none, but if so would have to have type Param from the nodes)
      // token: Token, dtype: TypeNode, id: IdNode
      List()
    )

    val description: Descr = TableInserter.describe(declr)
    val table = blankTable.addedMethod(description.asInstanceOf[MethodDescr])

    expr.table = table
    expr.name.id.table = table
    val returnExpected = dtype
    val returnGot = TypeProp.visit(expr)
    return returnExpected == returnGot;
  }

  // Expression: test() (declared as bool test() {})
  test(
    "`TypeProp` test: MethodCallExpr of BoolType propagates BoolType"
  ) {
    assert(testTypeMethod(ReturnType.bool, "bool"))
  }

  // Expression: test() (declared as int test() {})
  test(
    "`TypeProp` test: MethodCallExpr of IntType propagates IntType"
  ) {
    assert(testTypeMethod(ReturnType.int, "int"))
  }

  // Expression: test() (declared as void test() {})
  test(
    "`TypeProp` test: MethodCallExpr of VoidType propagates VoidType"
  ) {
    // Look above for a template (type method is basically the ame)

    // token: Keyword,
    // id: IdNode,
    // params: List[Param],
    // block: Block
    val declr: ASTVoidMethodDecl = ASTVoidMethodDecl(
      // Token (NOTE: unclear why it has to be a keyword and not a TypeNode...)
      Keyword("void", 0, 0),
      // Method name
      ASTIdNode(IdToken("test", 0, 0)),
      // No arguments
      List(),
      // Declaration
      ASTBlock(
        // Methods must start like this
        Mark("{", 0, 0),
        // No fields
        List(),
        // No statements
        List()
      )
    )

    // Technically not legal, so might not pass later, but whatever
    val expr: ASTMethodCallExpr = ASTMethodCallExpr(
      // Token
      IdToken("test", 0, 0),
      // MethodName (not sure why it was just IdNode for declr)
      ASTMethodName(
        // Token
        IdToken("test", 0, 0),
        // Id node with token in it
        ASTIdNode(IdToken("test", 0, 0))
      ),
      // Arguments (none, but if so would have to have type Param from the nodes)
      // token: Token, dtype: TypeNode, id: IdNode
      List()
    )

    val description: Descr = TableInserter.describe(declr)
    val table = blankTable.addedMethod(description.asInstanceOf[MethodDescr])

    expr.table = table
    expr.name.id.table = table
    val returnExpected = ReturnType.void
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1
  test("`TypeProp` test: IntLiteral propagates IntType") {
    val literal = ASTIntLiteral(IntToken("1", 0, 0))
    literal.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(literal)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 'a'
  test("`TypeProp` test: CharLiteral propagates IntType") {
    val literal = ASTCharLiteral(CharToken("a", 0, 0));
    literal.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(literal)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: true
  test("`TypeProp` test: BoolLiteral propagates BoolType") {
    val literal = ASTBoolLiteral(BoolToken("true", 0, 0));
    literal.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(literal)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: "test"
  // String literals can only ever be used in external functions, and the parser
  // prohibits them from being used ouside of a functional call. They don't really
  // have a type.
  test("`TypeProp` test: StringLiteral propagates VoidType") {
    val literal = ASTStringLiteral(StrToken("test", 0, 0));
    literal.table = blankTable
    val returnExpected = ReturnType.void
    val returnGot = TypeProp.visit(literal)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: len test
  test("`TypeProp` test: LenExpr propagates IntType") {
    val expr =
      ASTLenExpr(Keyword("len", 0, 0), ASTIdNode(IdToken("test", 0, 4)));
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 + 1
  test("`TypeProp` test: AddExpr propagates IntType") {
    val expr = ASTAddExpr(
      ArithOp("+", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 - 1
  test("`TypeProp` test: SubExpr propagates IntType") {
    val expr = ASTSubExpr(
      ArithOp("-", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 * 1
  test("`TypeProp` test: MulExpr propagates IntType") {
    val expr = ASTMulExpr(
      ArithOp("*", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 / 1
  test("`TypeProp` test: DivExpr propagates IntType") {
    val expr = ASTDivExpr(
      ArithOp("/", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 % 1
  test("`TypeProp` test: ModExpr propagates IntType") {
    val expr = ASTModExpr(
      ArithOp("%", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 < 1
  test("`TypeProp` test: LtExpr propagates BoolType") {
    val expr = ASTLtExpr(
      RelOp("<", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 > 1
  test("`TypeProp` test: GtExpr propagates BoolType") {
    val expr = ASTGtExpr(
      RelOp(">", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 <= 1
  test("`TypeProp` test: LeExpr propagates BoolType") {
    val expr = ASTLeExpr(
      RelOp("<=", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 >= 1
  test("`TypeProp` test: GeExpr propagates BoolType") {
    val expr = ASTGeExpr(
      RelOp(">=", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 == 1
  test("`TypeProp` test: EqExpr propagates BoolType") {
    val expr = ASTEqExpr(
      EqOp("==", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: 1 != 1
  test("`TypeProp` test: NeExpr propagates BoolType") {
    val expr = ASTNeExpr(
      EqOp("!=", 0, 2),
      ASTIntLiteral(IntToken("1", 0, 0)),
      ASTIntLiteral(IntToken("1", 0, 4))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: true && true
  test("`TypeProp` test: AndExpr propagates BoolType") {
    val expr = ASTAndExpr(
      CondOp("&&", 0, 5),
      ASTBoolLiteral(BoolToken("true", 0, 0)),
      ASTBoolLiteral(BoolToken("true", 0, 8))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: true || true
  test("`TypeProp` test: OrExpr propagates BoolType") {
    val expr = ASTOrExpr(
      CondOp("||", 0, 5),
      ASTBoolLiteral(BoolToken("true", 0, 0)),
      ASTBoolLiteral(BoolToken("true", 0, 8))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: -1
  test("`TypeProp` test: NegExpr propagates IntType") {
    val expr = ASTNegExpr(
      ArithOp("-", 0, 0),
      ASTIntLiteral(IntToken("1", 0, 1))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: !true
  test("`TypeProp` test: NotExpr propagates BoolType") {
    val expr = ASTNotExpr(
      LogOp("!", 0, 0),
      ASTBoolLiteral(BoolToken("true", 0, 1))
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: (true && true)
  test("`TypeProp` test: ParenExpr with Bool expr propogates BoolType") {
    val expr = ASTParenExpr(
      Mark("(", 0, 0),
      ASTAndExpr(
        CondOp("&&", 0, 6),
        ASTBoolLiteral(BoolToken("true", 0, 1)),
        ASTBoolLiteral(BoolToken("true", 0, 9))
      )
    )
    expr.table = blankTable
    val returnExpected = ReturnType.bool
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }

  // Expression: (1 + 1)
  test("`TypeProp` test: ParenExpr with Int expr propogates IntType") {
    val expr = ASTParenExpr(
      Mark("(", 0, 0),
      ASTAddExpr(
        ArithOp("+", 0, 3),
        ASTIntLiteral(IntToken("1", 0, 1)),
        ASTIntLiteral(IntToken("1", 0, 5))
      )
    )
    expr.table = blankTable
    val returnExpected = ReturnType.int
    val returnGot = TypeProp.visit(expr)
    assert(
      returnExpected == returnGot,
      "Expected: " + returnExpected.toString + " Got: " + returnGot.toString
    )
  }
}
