package edu.mit.compilers.codegen

import scala.collection.mutable.{Map => MutableMap}

// Basically will create an order of the blocks such that along any path the order is necessarily
// increasing strictly and monotonically. It's important for the linear allocator. While in theory
// the ids have this property it's not guaranteed.
case object BlockOrderer {
  // TODO unclear how we want to deal with this in loops...
  // is it a domination thing?
  def order(cfg: BasicBlock): Map[BasicBlock, Long] = {
    assert(
      cfg.functionHeader.getOrElse(
        throw new Exception("Provide function header to `BlockOrderer`")
      ) == cfg,
      "Need to be given function header (CFG) to order blocks"
    )

    // Init
    var worklist = List(cfg)
    var blockMap: MutableMap[BasicBlock, Long] = MutableMap()
    cfg.lineage.foreach(bb => blockMap(bb) = 0L)

    // Fixed point algorithm
    while (worklist.size > 0) {
      val bb: BasicBlock = worklist.head

      // Make sure that this basic block is bigger than all its parents if there are any
      blockMap(bb) = bb.parents
        // Ignore back-edges
        .filterNot(p => p.loop == Some(bb))
        // Make sure that this is bigger than all the parents
        .foldLeft(blockMap.get(bb).getOrElse(0L))((acc, p) =>
          acc.max(blockMap(p))
        ) + 1

      // Add all children that do not meet the property
      val add: List[BasicBlock] =
        bb.children
          // Ignore back-edges
          .filterNot(c => Some(c) == bb.loop)
          .filter(c => blockMap(c) <= blockMap(bb))
          .toList
      worklist = worklist.tail ++ add
    }
    // Make sure that we've covered all the blocks
    assert(blockMap.size == cfg.lineage.size)
    // Make sure that we were able to find an ordering that is valid
    assert(
      cfg.lineage.foldLeft(true)((oacc, bb) =>
        oacc && bb.parents
          .filterNot(p => p.loop == Some(bb))
          .foldLeft(true)((iacc, p) => iacc && blockMap(p) < blockMap(bb))
      )
    )
    blockMap.toMap
  }
}

// A way of ordering instructions that behaves like a 2-digit number in base
// max(block order, max num of instrs per block)
case class InstrOrder(blockOrder: Long, index: Long) {
  override def toString: String = {
    s"($blockOrder, $index)"
  }
  // START
  // Boilerplate generated by github copilot
  def <(that: InstrOrder): Boolean = {
    this.blockOrder < that.blockOrder || (this.blockOrder == that.blockOrder && this.index < that.index)
  }
  def >(that: InstrOrder): Boolean = {
    this.blockOrder > that.blockOrder || (this.blockOrder == that.blockOrder && this.index > that.index)
  }
  def ==(that: InstrOrder): Boolean = {
    this.blockOrder == that.blockOrder && this.index == that.index
  }
  def !=(that: InstrOrder): Boolean = {
    !(this == that)
  }
  def <=(that: InstrOrder): Boolean = {
    this < that || this == that
  }
  def >=(that: InstrOrder): Boolean = {
    this > that || this == that
  }
  // END
}

// Tentative way of ordering instructions... there may be a better way in the future...
case object InstrOrderer {
  def order(cfg: BasicBlock): Map[BasicBlock, Map[BasicInstr, InstrOrder]] = {
    val blockOrdering = BlockOrderer.order(cfg)
    var ordering: Map[BasicBlock, Map[BasicInstr, InstrOrder]] = Map()
    // For each block find the orderings for its instructions
    blockOrdering.foreach(pair => {
      val (block, blockOrder): (BasicBlock, Long) = pair

      // Order the instructions in that block
      var instrOrdering: Map[BasicInstr, InstrOrder] = Map()
      block.instrs.zipWithIndex.foreach(zpair => {
        val (instruction, index): (BasicInstr, Int) = zpair
        val ordering = InstrOrder(blockOrder, index.toLong)
        instrOrdering += (instruction -> ordering)
      })
      ordering += (block -> instrOrdering)
    })
    ordering
  }
}
